### ISSUE TITLE
Langenscheidt wird "Hurensohn" nicht in die top-10 aufnehmen. Ändern wir das Standard Wort zu Schabernack!

### ISSUE THREAD

**Issue by pagpeter** [hallowed/jugendwort-spammer#14]

**Comment by skyfrk** [comment]
Das ist doch Schabernack!

**Comment by lennardwalter** [comment]
Der gerade laufende PR fügt Argparse hinzu. Da wird man dann auch das Wort einstellen können. Obwohl Hurensohn doch ein so schönes Wort ist... :(
